### ISSUE TITLE
Upcoming web-rtc class

### ISSUE THREAD

**Issue by sfeeser** [alta3/sipgate#2]
Tracy sold a web-rtc class, where we will build a working web-rtc lab, or at least try to do so. I would like to get a jump on it, and actually build something useful. @bryfry , please give me feedback on this idea. It is a fully contained sip access, nothing external required, and hides the web-rtc access details, allowing focus on SIP. Since a dockerfile will create this container, the details will be available for the upcoming web-rtc class

![image](https://user-images.githubusercontent.com/13711668/209225827-ff38f30d-2c0f-45ee-b288-03915b2cc9f9.png)

**Comment by bryfry** [comment]
Reviewed and implemented by @sfeeser to great success! Closing.
